<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="" type="image/png">

    <link rel="stylesheet" href="stayle/index.css">
    <link rel="stylesheet" href="stayle/nav.css">
    <link rel="stylesheet" href="stayle/scrol.css">
    <link rel="shortcut icon" href="/img/logo.svg" type="image/x-icon">
    <title>PolitWay</title>


    <!-- ШРИФТЫ  -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@800&display=swap" rel="stylesheet">
        <div class="nav">
            <img src="/img/Flag.svg" alt="" class="flag">
            <img src="/img/ButtonZSU.svg" alt="" class="flag_btn">

        <div class="logo">
            <img src="/img/TextLogo.svg" alt="" class="logo_img">
        </div>


        <div class="btn">
                <div style="background-image: linear-gradient(29.32deg, #FFC149 -15.55%, rgba(47, 251, 92, 0) 65.8%);" class="hexagon"></div>
                <a class="btn_a" href=" http://game6.falixserver.net:52515/#world;flat;2228,64,5294;1">Мапа</a>

                <div style="background-image: linear-gradient(29.32deg, #2FFB5C -15.55%, rgba(47, 251, 92, 0) 65.8%);" class="hexagon"></div>
                <a class="btn_a" href="https://donatello.to/PolitWay">Донат</a>
                
                <div style="background-image: linear-gradient(29.32deg, #4558ff -15.55%, rgba(47, 251, 92, 0) 65.8%);" class="hexagon"></div>
                <a class="btn_a" href="rules">Правила</a>
                
                <div style="background-image: linear-gradient(29.32deg,#ff4545 -15.55%, rgba(47, 251, 92, 0) 65.8%);" class="hexagon"></div>
                <a class="btn_a" href="index">Таблиця</a>

              

            <div class="btn_menu">
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
            </div> 
        </div>
    </div></head><br><link rel="stylesheet" href="stayle/table.css">        <div class="text">
            <h1>Таблиця країн</h1>
            <h3>Команди, що можуть стати в нагоді при зміненні інформації <br>
щодо вашої країни, можете знайти 
<div style="background-image: linear-gradient(1.86deg, #4393F2 -10.63%, rgba(67, 147, 242, 0) 77.68%);" class="hexagon_text3"></div></h3>
             <a class="text_btn" href="/index.php">тут</a>
             <div style="background-image: linear-gradient(20.16deg, #2F45FB -16.87%, rgba(47, 69, 251, 0) 68.23%);" class="hexagon_text1"></div>
             <div style="background-image: linear-gradient(203.32deg, #2F45FB 15.06%, rgba(47, 69, 251, 0) 68.37%);" class="hexagon_text2"></div>

        </div>
<br />
<div class="dtable">
    <table>
    <div class="dtable_inputs">
        <form action="index.php" method="get">
            <input type="text"  class="dtable_input" name="search" id="" placeholder="Ведіть назву нації">
            <input type="submit"class="dtable_btn" value="Пошук">
        </form>
    </div>
    <tr style="background-color:#ffffff00;">
        <th style="border-right: 1px solid #ffffff;">Нація</th>
        <th>Столиця</th>
        <th style="border-left: 1px solid #ffffff;">Правитель</th>
        <th style="border-left: 1px solid #ffffff;">О.К</th>
    </tr>
<br />
<b>Warning</b>:  Undefined array key "search" in <b>/sites/politary.pp.ua/index.php</b> on line <b>57</b><br />
    <tr>
        <td><a>Подільське Князівство</a></td>
                        <td><a>Кам'янець Подільський</a></td>
                <td><a>SenderOk</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Королівство Шотландія</a></td>
                        <td><a>Скун</a></td>
                <td><a>Jurgen20102010</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Османьска Імперія </a></td>
                        <td><a>Стамбул</a></td>
                <td><a>MixLever1</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Кримське Ханство</a></td>
                        <td><a>Бахчисарай</a></td>
                <td><a>Ypele</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Золота орда</a></td>
                        <td><a>Сарай-Бату</a></td>
                <td><a>power_love2</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Королівство Данія </a></td>
                        <td><a>Копенгаген </a></td>
                <td><a>MenficksUkraine</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Англія</a></td>
                        <td><a>Англія</a></td>
                <td><a>_TheFireFox_</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Франція</a></td>
                        <td><a>Париж</a></td>
                <td><a>Arturc_Zelenskiy</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>Тевтонський Орден</a></td>
                        <td><a>Рига</a></td>
                <td><a>valik77777</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>1</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>Сан-NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
                <tr>
        <td><a>NPC</a></td>
                        <td><a>NPC</a></td>
                <td><a>NPC</a></td>
                <td><a>0</a></td>
            </tr>
<tr>
    <td style="border:300px;"></td>
    <td style="border:300px;"></td>
    <td style="border:300px;"></td>
    <td style="border:300px;"></td>
</tr>
</table>
<br><br><br><br><br><br>
<footer class="footer"></footer>
</div>